apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aktivitetskort-test-v3
  namespace: dab
  labels:
    team: dab
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete # delete = ingen compaction
    retentionHours: -1 # evig retention
    minimumInSyncReplicas: 2
    partitions: 4
    replication: 2
  acl:
    - team: dab
      application: aktivitet-arena-acl
      access: write
    - team: pto
      application: veilarbaktivitet
      access: read
    - team: pto
      application: pto-kafka-manager
      access: read
