# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
  gradle:
    type: maven-repository
    url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
    username: x-access-token
    password: no-secret-required

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"