# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbaktivitet
team: oppfolging
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: veilarbaktivitet/internal/isAlive
    initialDelay: 60
  readiness:
    path: veilarbaktivitet/internal/isReady
    initialDay: 60
prometheus:
  enabled: true
  path: veilarbaktivitet/internal/metrics
resources:
  limits:
    cpu: 2
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 768Mi
fasitResources:
  used:
  - alias: loadbalancer:veilarbaktivitet
    resourceType: loadbalancerconfig
  - alias: veilarbaktivitetDataSource
    resourceType: datasource
  - alias: srvveilarbaktivitet
    resourceType: credential
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: veilarbaktivitet.properties
    resourceType: applicationproperties
  - alias: securityTokenService
    resourceType: baseUrl
  - alias: abac.pdp.endpoint
    resourceType: restservice
  - alias: Aktoer_v2
    resourceType: webserviceendpoint
  - alias: veilArbOppfolgingAPI
    resourceType: restservice
  - alias: virksomhet:TiltakOgAktivitet_v1
    resourceType: webserviceendpoint
  - alias: unleash-api
    resourceType: restservice

  # ISSO
  - alias: isso-host
    resourceType: baseurl
  - alias: isso-jwks
    resourceType: baseurl
  - alias: isso-issuer
    resourceType: baseurl
  - alias: isso.isalive
    resourceType: baseurl
  - alias: isso-rp-user
    resourceType: credential
  - alias: veilarblogin.redirect-url
    resourceType: restservice
  - alias: aad_b2c_clientid
    resourceType: credential
  - alias: veilarbazureadproxy_discovery
    resourceType: restservice

  exposed:
  - alias: veilArbAktivitetAPI
    resourceType: restservice
    path: /veilarbaktivitet/api

alertProfiles:
  - common-java-modules
