kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbaktivitet
  namespace: default
  cluster: prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbaktivitet/veilarbaktivitet:{{version}}
  ingresses:
    - https://veilarbaktivitet.nais.adeo.no
    - https://app.adeo.no/veilarbaktivitet
  port: 8080
  prometheus:
    enabled: true
    path: veilarbaktivitet/internal/prometheus
  liveness:
    path: veilarbaktivitet/internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: veilarbaktivitet/internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 4048Mi
    requests:
      cpu: 200m
      memory: 1536Mi
  envFrom:
    - configmap: pto-config
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarbaktivitet-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/prod/srvveilarbaktivitet
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarbaktivitet/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  leaderElection: true
  env:
    - name: APP_ENVIRONMENT_NAME
      value: p
