kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbaktivitet
  namespace: {{namespace}}
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbaktivitet/veilarbaktivitet:{{version}}
  ingresses:
    - https://veilarbaktivitet-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/veilarbaktivitet
    - https://app-{{namespace}}.dev.adeo.no/veilarbaktivitet
  port: 8080
  prometheus:
    enabled: true
    path: veilarbaktivitet/internal/prometheus
  liveness:
    path: veilarbaktivitet/internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: veilarbaktivitet/internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarbaktivitet_{{namespace}}-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/dev/srvveilarbaktivitet
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarbaktivitet/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/dev/config/veilarbaktivitet_{{namespace}}
        mountPath: /var/run/secrets/nais.io/oracle_config
  webproxy: true
  leaderElection: true
  env:
    - name: APP_ENVIRONMENT_NAME
      value: {{namespace}}
