kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbaktivitet
  namespace: default
  cluster: prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbaktivitet/veilarbaktivitet:{{version}}
  ingresses:
    - https://veilarbaktivitet.nais.adeo.no
    - https://app.adeo.no/veilarbaktivitet
  port: 8080
  prometheus:
    enabled: true
    path: veilarbaktivitet/internal/metrics
  liveness:
    path: veilarbaktivitet/internal/isAlive
    port: 8080
    initialDelay: 20
  readiness:
    path: veilarbaktivitet/internal/isReady
    port: 8080
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1536Mi
  configMaps:
    files:
      - pto-config
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarbaktivitet-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/prod/srvveilarbaktivitet
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarbaktivitet/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  env:
    - APPDYNAMICS_AGENT_ACCOUNT_NAME
    - APPDYNAMICS_CONTROLLER_HOST_NAME
    - APPDYNAMICS_CONTROLLER_PORT
    - APPDYNAMICS_CONTROLLER_SSL_ENABLED
