kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbaktivitet
  namespace: pto
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbaktivitet/veilarbaktivitet:{{version}}
  ingresses:
    - https://veilarbaktivitet-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarbaktivitet
    - https://app-q1.dev.adeo.no/veilarbaktivitet
  port: 8080
  prometheus:
    enabled: true
    path: veilarbaktivitet/internal/prometheus
  liveness:
    path: veilarbaktivitet/internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: veilarbaktivitet/internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarbaktivitet_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/dev/srvveilarbaktivitet
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/preprod/fss/veilarbaktivitet/q1
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/dev/config/veilarbaktivitet_q1
        mountPath: /var/run/secrets/nais.io/oracle_config
  webproxy: true
  leaderElection: true
  secureLogs:
    enabled: true
  env:
    - name: APP_ENVIRONMENT_NAME
      value: q1
    - name: ENDRING_PA_AKTIVITET_TOPIC
      value: aapen-fo-endringPaaAktivitet-v4-q1
    - name: OPPFOLGING_AVSLUTTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-oppfolgingAvsluttet-v1-q1
    - name: KVP_AVSLUTTET_TOPIC
      value: aapen-arbeidsrettetOppfolging-kvpAvsluttet-v1-q1
