/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "veilarbaktivitet"


pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
