CREATE TABLE SLETTEDE_AKTIVITETER(
  AKTIVITET_ID        NUMBER(19)      NOT NULL,
  TIDSPUNKT           TIMESTAMP(6)    NOT NULL
);

CREATE INDEX SLETTET_DATO_AKTIVITET_IDX ON SLETTEDE_AKTIVITETER (TIDSPUNKT);

CREATE VIEW DVH_SLETTEDE_AKTIVITETER AS (
  SELECT
    AKTIVITET_ID,
    TIDSPUNKT
  FROM SLETTEDE_AKTIVITETER
);