create table AKTIVITET
(
  AKTIVITET_ID NUMBER(19) not null
    constraint AKTIVITET_PK
    primary key,
  AKTOR_ID NVARCHAR2(255),
  TITTEL NVARCHAR2(255),
  TYPE NVARCHAR2(255),
  AVSLUTTET_DATO TIMESTAMP(6),
  AVSLUTTET_KOMMENTAR NVARCHAR2(255),
  LAGT_INN_AV NVARCHAR2(255),
  FRA_DATO TIMESTAMP(6),
  TIL_DATO TIMESTAMP(6),
  LENKE NVARCHAR2(2000),
  OPPRETTET_DATO TIMESTAMP(6),
  STATUS NVARCHAR2(255) not null,
  BESKRIVELSE CLOB,
  AVTALT NUMBER(1) default 0 not null,
  VERSJON NUMBER(19) default 0 not null
);
create index AKTIVITET_AKTOR_IDX on AKTIVITET (AKTOR_ID);
create SEQUENCE AKTIVITET_ID_SEQ start with 1 INCREMENT BY 1;

create table EGENAKTIVITET
(
  AKTIVITET_ID NUMBER(19)
    constraint EGENAKTIVITET_FK
    references AKTIVITET,
  HENSIKT NVARCHAR2(255),
  OPPFOLGING NVARCHAR2(255)
);
create index EGENAKTIVITET_FK on EGENAKTIVITET (AKTIVITET_ID);

create table ENDRINGSLOGG
(
  ID NUMBER(19) not null,
  AKTIVITET_ID NUMBER(19) not null
    constraint ENDRINGSLOGG_FK
    references AKTIVITET,
  ENDRINGS_BESKRIVELSE NVARCHAR2(255),
  ENDRET_AV NVARCHAR2(255),
  ENDRINGS_DATO TIMESTAMP(6)
);
create index ENDRINGSLOGG_AKTIVITET_IDX on ENDRINGSLOGG (AKTIVITET_ID);
create sequence ENDRINGSLOGG_ID_SEQ start with 1 increment by 1;

create table STILLINGSSOK
(
  AKTIVITET_ID NUMBER(19)
    constraint STILLINGSSOK_AKTIVITET_FK
    references AKTIVITET,
  ARBEIDSGIVER NVARCHAR2(255),
  STILLINGSTITTEL NVARCHAR2(255),
  KONTAKTPERSON NVARCHAR2(255),
  ETIKETT NVARCHAR2(255),
  ARBEIDSSTED NVARCHAR2(255)
);
create index STILLINGSSOK_AKTIVITET_IDX on STILLINGSSOK (AKTIVITET_ID)

