ALTER TABLE AKTIVITET ADD MAL_ID NVARCHAR2(3);
ALTER TABLE AKTIVITET ADD LEST_AV_BRUKER_FORSTE_GANG TIMESTAMP(6);
ALTER TABLE AKTIVITET ADD AUTOMATISK_OPPRETTET NUMBER(1) DEFAULT 0 NOT NULL;

-- Setter feltet på alle aktiviteter slik at vi kun lager metrikker for framtidige aktiviteter
UPDATE AKTIVITET SET LEST_AV_BRUKER_FORSTE_GANG = CURRENT_TIMESTAMP;