INSERT INTO AKTIVITET_TYPE (AKTIVITET_TYPE_KODE, AKTIVITET_TYPE_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('EGENAKTIVITET', 'Egendefinert aktivitet', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO AKTIVITET_TYPE (AKTIVITET_TYPE_KODE, AKTIVITET_TYPE_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('JOBBSOEKING', 'Stilling søk aktivitet', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO AKTIVITET_TYPE (AKTIVITET_TYPE_KODE, AKTIVITET_TYPE_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('SOKEAVTALE', 'Aktivtet som beskriver hvor mange stilligner som skal søkes på en gitt periode',
        CURRENT_TIMESTAMP,
        '***REMOVED***');


INSERT INTO AKTIVITET_LIVSLOPSTATUS (AKTIVITET_LIVSLOP_KODE, AKTIVITET_LIVSLOP_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('PLANLAGT', 'Planlagt status', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO AKTIVITET_LIVSLOPSTATUS (AKTIVITET_LIVSLOP_KODE, AKTIVITET_LIVSLOP_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('GJENNOMFORT', 'Pågår status', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO AKTIVITET_LIVSLOPSTATUS (AKTIVITET_LIVSLOP_KODE, AKTIVITET_LIVSLOP_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('FULLFORT', 'Fullført status', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO AKTIVITET_LIVSLOPSTATUS (AKTIVITET_LIVSLOP_KODE, AKTIVITET_LIVSLOP_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('BRUKER_ER_INTERESSERT', 'Foreslått status', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO AKTIVITET_LIVSLOPSTATUS (AKTIVITET_LIVSLOP_KODE, AKTIVITET_LIVSLOP_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('AVBRUTT', 'Avbrutt status', CURRENT_TIMESTAMP, '***REMOVED***');


INSERT INTO ETIKETT (ETIKETT_KODE, ETIKETT_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('SOKNAD_SENDT', 'Søknad sendt etikett', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO ETIKETT (ETIKETT_KODE, ETIKETT_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('INNKALT_TIL_INTERVJU', 'Inkalt til intervju etikett', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO ETIKETT (ETIKETT_KODE, ETIKETT_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('AVSLAG', 'Fått avslag etikett', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO ETIKETT (ETIKETT_KODE, ETIKETT_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('JOBBTILBUD', 'Fått jobbtilbud etikett', CURRENT_TIMESTAMP, '***REMOVED***');


INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, TRANSAKSJONS_TYPE_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('OPPRETTET', 'Aktiviten er opprettet', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, TRANSAKSJONS_TYPE_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('STATUS_ENDRET', 'Aktivitetstatus er endret', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, TRANSAKSJONS_TYPE_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('DETALJER_ENDRET', 'Detaljer på aktiviteten er endret', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, TRANSAKSJONS_TYPE_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('AVTALT', 'Aktiviteten er satt til avtalt', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, TRANSAKSJONS_TYPE_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('AVTALT_DATO_ENDRET', 'Fristen på avtalt aktivitet er endret', CURRENT_TIMESTAMP, '***REMOVED***');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, TRANSAKSJONS_TYPE_BESKRIVELSE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('ETIKETT_ENDRET', 'Etiketten på aktiviteten er endret', CURRENT_TIMESTAMP, '***REMOVED***');