create table SOKEAVTALE
(
  AKTIVITET_ID NUMBER(19)
    constraint SOKEAVTALE_FK
    references AKTIVITET,
  ANTALL NUMBER(19),
  AVTALE_OPPFOLGING CLOB
);
create index SOKEAVTALE_FK on EGENAKTIVITET (AKTIVITET_ID);