UPDATE AKTIVITET SET STATUS='PLANLAGT' WHERE STATUS='GJENNOMFORT'; -- Brukes for å få lov til å endre FK fra GJENNOMFORT til GJENNOMFORES --
UPDATE AKTIVITET_LIVSLOPSTATUS_TYPE SET AKTIVITET_LIVSLOP_KODE='GJENNOMFORES' WHERE AKTIVITET_LIVSLOP_KODE = 'GJENNOMFORT';


ALTER TABLE AKTIVITET RENAME COLUMN TYPE TO AKTIVITET_TYPE_KODE;
ALTER TABLE AKTIVITET RENAME COLUMN STATUS TO LIVSLOPSTATUS_KODE;


ALTER TABLE SOKEAVTALE RENAME COLUMN ANTALL TO ANTALL_STILLINGER_SOKES;