CREATE OR REPLACE VIEW DVH_AKTIVITET AS (
  SELECT
    AKTIVITET_ID,
    VERSJON,
    TRANSAKSJONS_TYPE,
    AKTOR_ID,
    TITTEL,
    AKTIVITET_TYPE_KODE,
    AVSLUTTET_KOMMENTAR,
    LAGT_INN_AV,
    FRA_DATO,
    TIL_DATO,
    LENKE,
    OPPRETTET_DATO,
    ENDRET_DATO,
    ENDRET_AV,
    LIVSLOPSTATUS_KODE,
    BESKRIVELSE,
    AVTALT,
    HISTORISK_DATO,
    GJELDENDE
  FROM AKTIVITET
);

ALTER TABLE AKTIVITET DROP COLUMN AVSLUTTET_DATO;