apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: veilarbaktivitet-error-rate
  namespace: dab
  labels:
    team: dab
spec:
  groups:
    - name: SLOs-nginx_ingress_controller_requests
      rules:
        - alert: veialrbaktivitetIngerssMetrikkenFinnesIkke
          annotations:
            message: 'veilarbaktivitet metrikken eksisterer ikke i nginx_ingress_controller_requests'
          expr: |
            absent(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab"})
          for: 15m
          labels:
            namespace: dab
            service: veilarbaktivitet
            severity: warning
        - alert: VeilarbaktivitetErrorBudgetBurn
          annotations:
            message: 'High error budget burn for service=veilarbaktivitet (current value: {{ $value }})'
          expr: |
            sum(nginx_ingress_controller_requests:burnrate5m{service="veilarbaktivitet", namespace="dab"}) > (14.40 * (1-0.99900))
            and
            sum(nginx_ingress_controller_requests:burnrate1h{service="veilarbaktivitet", namespace="dab"}) > (14.40 * (1-0.99900))
            and
            mellom_kl_06_og_23
          for: 2m
          labels:
            namespace: dab
            service: veilarbaktivitet
            severity: critical
        - alert: VeilarbaktivitetErrorBudgetBurn
          annotations:
            message: 'High error budget burn for service=veilarbaktivitet (current value: {{ $value }})'
          expr: |
            sum(nginx_ingress_controller_requests:burnrate30m{service="veilarbaktivitet", namespace="dab"}) > (6.00 * (1-0.99900))
            and
            sum(nginx_ingress_controller_requests:burnrate6h{service="veilarbaktivitet", namespace="dab"}) > (6.00 * (1-0.99900))
            and
            mellom_kl_06_og_23
          for: 15m
          labels:
            namespace: dab
            service: veilarbaktivitet
            severity: critical
        - alert: VeilarbaktivitetErrorBudgetBurn
          annotations:
            message: 'High error budget burn for service=veilarbaktivitet (current value: {{ $value }})'
          expr: |
            sum(nginx_ingress_controller_requests:burnrate2h{service="veilarbaktivitet", namespace="dab"}) > (3.00 * (1-0.99900))
            and
            sum(nginx_ingress_controller_requests:burnrate1d{service="veilarbaktivitet", namespace="dab"}) > (3.00 * (1-0.99900))
          for: 1h
          labels:
            namespace: dab
            service: veilarbaktivitet
            severity: warning
        - alert: VeilarbaktivitetErrorBudgetBurn
          annotations:
            message: 'High error budget burn for service=veilarbaktivitet (current value: {{ $value }})'
          expr: |
            sum(nginx_ingress_controller_requests:burnrate6h{service="veilarbaktivitet", namespace="dab"}) > (1.00 * (1-0.99900))
            and
            sum(nginx_ingress_controller_requests:burnrate3d{service="veilarbaktivitet", namespace="dab"}) > (1.00 * (1-0.99900))
          for: 3h
          labels:
            service: veilarbaktivitet
            severity: warning
        - record: mellom_kl_06_og_23
          expr: |
            (hour() >= 6 and hour() <= 23)

        - expr: |
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab", status=~"5.."}[1d]))
            /
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab"}[1d]))
          labels:
            service: veilarbaktivitet
          record: nginx_ingress_controller_requests:burnrate1d
        - expr: |
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab", status=~"5.."}[1h]))
            /
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab"}[1h]))
          labels:
            service: veilarbaktivitet
          record: nginx_ingress_controller_requests:burnrate1h
        - expr: |
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab", status=~"5.."}[2h]))
            /
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab"}[2h]))
          labels:
            service: veilarbaktivitet
          record: nginx_ingress_controller_requests:burnrate2h
        - expr: |
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab", status=~"5.."}[30m]))
            /
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab"}[30m]))
          labels:
            service: veilarbaktivitet
          record: nginx_ingress_controller_requests:burnrate30m
        - expr: |
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet" , namespace="dab", status=~"5.."}[3d]))
            /
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab"}[3d]))
          labels:
            service: veilarbaktivitet
          record: nginx_ingress_controller_requests:burnrate3d
        - expr: |
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab", status=~"5.."}[5m]))
            /
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab"}[5m]))
          labels:
            service: veilarbaktivitet
          record: nginx_ingress_controller_requests:burnrate5m
        - expr: |
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab", status=~"5.."}[6h]))
            /
            sum(rate(nginx_ingress_controller_requests{service="veilarbaktivitet", namespace="dab"}[6h]))
          labels:
            service: veilarbaktivitet
          record: nginx_ingress_controller_requests:burnrate6h
