apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: veilarbaktivitet-alarm
  namespace: dab
  labels:
    team: dab
spec:
  receivers:
    slack:
      channel: '#team_dab_alerts'
      prependText: '<!here> | '
  alerts:
    - alert: Høy feilrate veilarbaktivitet
      expr: |
        (((
        sum(rate(traefik_backend_requests_total{backend=~"^veilarbaktivitet.intern.nav.no",protocol="http",code!~'(^[23].*)|(^502)'}[5m] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^veilarbaktivitet.intern.nav.no",protocol="http"}[5m]) ) )  > (14.4*0.001))
        and ( (
        sum(rate(traefik_backend_requests_total{backend=~"^veilarbaktivitet.intern.nav.no",protocol="http",code!~'(^[23].*)|(^502)'}[1h] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^veilarbaktivitet.intern.nav.no",protocol="http"}[1h] ) ) )  > (14.4*0.001) ))
        or ( ( (
        sum(rate(traefik_backend_requests_total{backend=~"^veilarbaktivitet.intern.nav.no",protocol="http",code!~'(^[23].*)|(^502)'}[30m] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^veilarbaktivitet.intern.nav.no",protocol="http"}[30m] ) ) )  > (6*0.001) )
        and ( (
        sum(rate(traefik_backend_requests_total{backend=~"^veilarbaktivitet.intern.nav.no",protocol="http",code!~'(^[23].*)|(^502)'}[6h] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^veilarbaktivitet.intern.nav.no",protocol="http"}[6h] ) ) )  > (6*0.001)))
      for: 1s
      severity: danger
      description: Høy feilrate mot veilarbaktivitet.
      action: https://logs.adeo.no/goto/9106e407dee95bb4692f316564dd5330   https://grafana.nais.io/d/000000283/nais-app-dashbord?orgId=1&var-interval=$__auto_interval_interval&var-datasource=prod-fss&var-team=pto&var-app=veilarbaktivitet&var-namespace=All&var-docker_image=5e399fce17a0617acda62a3b4c969210d05abc17&var-ingress_url=All&from=now-6h&to=now
      sla: se på denne så fort som mulig (innefor arbeidstid)
    - alert: Flere feil mot brukernotifikasjon
      for: 1s
      description: fått feilmelding fra dokument om brukernotifikasjon
      sla: se på denne så fort som mulig (innefor arbeidstid)
      action: https://logs.adeo.no/goto/e3aeb611c66c132e09a5d40c964014cc
      severity: danger
      expr: |
        sum(increase(brukernotifikasjon_kvittering_mottatt_total{status="FEILET", app="veilarbaktivitet"}[5m])) > 10
    - alert: Flere feil med sending av smser
      for: 1h
      description: fåt feil med sending av smser
      sla: se på denne så fort som mulig (innefor arbeidstid)
      action: https://logs.adeo.no/goto/fb05eeccec47431fc4dc2b236bec346d
      severity: warning
      expr: |
        sum(increase(antalSMSFeilet_total{application="veilarbaktivitet"}[5m])) > 0.8
    - alert: feil ved deploy?
      expr: 'kube_deployment_status_replicas_unavailable{deployment="veilarbaktivitet"} > 0'
      for: 10m
      action: https://logs.adeo.no/goto/6fc98f8662b9893c80c103ba3a30fbfa
      description: feilet deploy?
      severity: warning
    - alert:  Feil med ekstern varsel kvitering
      expr: 'max(brukernotifikasjon_mangler_kvittering{application="veilarbaktivitet"}) > 0.8'
      for: 10m
      action: https://logs.adeo.no/goto/6fc98f8662b9893c80c103ba3a30fbfa
      description: forskinget kvitering på externvarsel
      severity: warning
    - alert: applikasjon nede
      expr: kube_deployment_status_replicas_available{deployment="veilarbaktivitet"} == 0
      for: 2m
      description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod -l app={{ $labels.app }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l app={{ $labels.app }} -n {{ $labels.namespace }}` for logger"
    - alert: høy feilrate i logger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="veilarbaktivitet",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="veilarbaktivitet"}[3m]))) > 10
      for: 3m
      action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
    - alert: feil i selftest
      expr: selftests_aggregate_result_status{app="veilarbaktivitet"} > 0
      for: 1m
      action: "Sjekk app {{ $labels.app }} i namespace {{ $labels.kubernetes_namespace }} sine selftest for å se hva som er galt"
    - alert: Teknisk feil i konsumering av rekrutteringsbistand-statusoppdatering-v1
      for: 3m
      description: Teknisk feil i kafka consumer
      sla: se på denne så fort som mulig (innefor arbeidstid)
      action: https://logs.adeo.no/goto/e3aeb611c66c132e09a5d40c964014cc
      severity: danger
      expr: |
        sum(rate(kafka_consume_rekrutteringsbistand_statusoppdatering_seconds_count{exception!='none'}[3m])) > 0.0
    - alert: Funksjonell feil i konsumering av aktivitetskort
      for: 3m
      description: Funksjonell feil i konsumering av aktivitetskort
      sla: se på denne når du kan (innenfor arbeidstid)
      action: https://logs.adeo.no/goto/06fca5c0-6f24-11ed-95b0-83aabf5238d7
      severity: warning
      expr: |
        sum(increase(aktivitetskort_funksjonell_feil_total[1d])) > 0.0
    - alert: Teknisk feil i konsumering av aktivitetskort
      for: 3m
      description: Teknisk feil i konsumering av aktivitetskort
      sla: se på denne så fort som mulig (innenfor arbeidstid)
      action: https://logs.adeo.no/goto/06fca5c0-6f24-11ed-95b0-83aabf5238d7
      severity: danger
      expr: |
        sum(increase(aktivitetskort_teknisk_feil_total[1m])) > 10.0