apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: veilarbaktivitet-alarm
  namespace: pto
  labels:
    team: pto
spec:
  receivers:
    slack:
      channel: '#team_dab_alerts_dev'
      prependText: ' '
  alerts:
    - alert: Høy feilrate veilarbaktivitet
      expr: |
        (((
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbaktivitet|veilarbaktivitet.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbaktivitet",protocol="http",code!~'(^[23].*)|(^502)'}[5m] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbaktivitet|veilarbaktivitet.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbaktivitet",protocol="http"}[5m]) ) )  > (14.4*0.001) )
        and ( (
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbaktivitet|veilarbaktivitet.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbaktivitet",protocol="http",code!~'(^[23].*)|(^502)'}[1h] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbaktivitet|veilarbaktivitet.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbaktivitet",protocol="http"}[1h] ) ) )  > (14.4*0.001) ))
        or ( ( (
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbaktivitet|veilarbaktivitet.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbaktivitet",protocol="http",code!~'(^[23].*)|(^502)'}[30m] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbaktivitet|veilarbaktivitet.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbaktivitet",protocol="http"}[30m] ) ) )  > (6*0.001) )
        and ( (
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbaktivitet|veilarbaktivitet.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbaktivitet",protocol="http",code!~'(^[23].*)|(^502)'}[6h] ) ) /
        sum(rate(traefik_backend_requests_total{backend=~"^app-q1.adeo.no/veilarbaktivitet|veilarbaktivitet.nais.adeo.no/|^app-q1.dev.adeo.no/veilarbaktivitet",protocol="http"}[6h] ) ) )  > (6*0.001)))
      for: 1s
      severity: danger
      description: Høy feilrate mot veilarbaktivitet.
      action: https://grafana.nais.io/d/z4LNWq-Mz/dab-alarmer \n https://logs.adeo.no/goto/6fc98f8662b9893c80c103ba3a30fbfa
      sla: se på denne så fort som mulig (innefor arbeidstid)
    - alert: Feil mot brukernotifikasjon
      for: 1s
      description: fått feilmelding fra dokument om burekrnotifikasjon
      sla: se på denne i løpet av de neste dagene.
      severity: warning
      action: https://logs.adeo.no/goto/e3aeb611c66c132e09a5d40c964014cc
      expr: |
        sum(increase(brukernotifikasjon_kvittering_mottatt_total{status="FEILET", app="veilarbaktivitet"}[5m])) > 0.5
    - alert: Feil mot brukernotifikasjon
      for: 1s
      description: fått feilmelding fra dokument om burekrnotifikasjon
      sla: se på denne i løpet av de neste dagene.
      action: https://logs.adeo.no/goto/e3aeb611c66c132e09a5d40c964014cc
      severity: warning
      expr: |
        sum(increase(brukernotifikasjon_kvittering_mottatt_total{status="FEILET", app="veilarbaktivitet"}[5m])) > 0.5
    - alert: Flere feil mot brukernotifikasjon
      for: 1s
      description: fått feilmelding fra dokument om burekrnotifikasjon
      sla: se på denne så fort som mulig (innefor arbeidstid)
      action: https://logs.adeo.no/goto/e3aeb611c66c132e09a5d40c964014cc
      severity: danger
      expr: |
        sum(increase(brukernotifikasjon_kvittering_mottatt_total{status="FEILET", app="veilarbaktivitet"}[5m])) > 10
    - alert: Feil mot brukernotifikasjon
      for: 1s
      description: Ikke fåt kvitering fra brukernotifikasjon
      sla: se på denne i løpet av de neste dagene.
      action: https://logs.adeo.no/goto/e3aeb611c66c132e09a5d40c964014cc
      severity: warning
      expr: |
        avg(brukernotifikasjon_mangler_kvittering{application="veilarbaktivitet"}) > 0.5
    - alert: feil ved deploy?
      expr: 'kube_deployment_status_replicas_unavailable{deployment="veilarbaktivitet"} > 0'
      for: 10m
      action: https://logs.adeo.no/goto/6fc98f8662b9893c80c103ba3a30fbfa
      description: feilet deploy?
      severity: warning
    - alert: Mange tekniske feil i konsumering av rekrutteringsbistand-statusoppdatering-v1
      for: 1s
      description: Teknisk feil i kafka consumer
      sla: se på denne så fort som mulig (innefor arbeidstid)
      action: https://logs.adeo.no/goto/e3aeb611c66c132e09a5d40c964014cc
      severity: danger
      expr: |
        sum(rate(kafka_consume_rekrutteringsbistand_statusoppdatering{success=false, app="veilarbaktivitet"}[1m])) > 10