kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbaktivitet
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbaktivitet/veilarbaktivitet:{{version}}
  ingresses:
    - https://veilarbaktivitet.nais.adeo.no
    - https://app.adeo.no/veilarbaktivitet
    - https://veilarbaktivitet.prod-fss-pub.nais.io
  port: 8080
  prometheus:
    enabled: true
    path: veilarbaktivitet/internal/prometheus
  liveness:
    path: veilarbaktivitet/internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: veilarbaktivitet/internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 4
    max: 8
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 4048Mi
    requests:
      cpu: 200m
      memory: 1536Mi
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
    - secret: veilarbaktivitet-unleash-api-token
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/veilarbaktivitet-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /serviceuser/data/prod/srvveilarbaktivitet
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /kv/prod/fss/veilarbaktivitet/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/prod/config/veilarbaktivitet
        mountPath: /var/run/secrets/nais.io/oracle_config
  webproxy: true
  leaderElection: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbapi
          namespace: pto
          cluster: prod-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: prod-fss
        - application: aktivitetsplan
          namespace: pto
          cluster: prod-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: prod-gcp
    outbound:
      external:
        - host: dab-unleash-api.nav.cloud.nais.io
        - host: orkivar.intern.nav.no
  env:
    - name: APP_ENVIRONMENT_NAME
      value: p
    - name: POAO_TILGANG_SCOPE
      value: api://prod-fss.poao.poao-tilgang/.default
    - name: ADMIN_GROUPS
      value: dfc550d0-c5bf-4208-8b2b-3542bb8b5b15
    - name: ARENA_AKTIVITET_DATOFILTER
      value: "2017-12-04"
    - name: ORKIVAR_URL
      value: "https://orkivar.intern.nav.no"
    - name: VEILARBDIALOG_URL
      value: http://veilarbdialog.pto.svc.nais.local/veilarbdialog
    - name: KAFKA_ENABLED
      value: "true"
