kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbaktivitet
  namespace: dab
  labels:
    team: dab
spec:
  image: ghcr.io/navikt/veilarbaktivitet/veilarbaktivitet:{{version}}
  ingresses:
    - https://veilarbaktivitet.intern.nav.no
  port: 8080
  prometheus:
    enabled: true
    path: veilarbaktivitet/internal/prometheus
  liveness:
    path: veilarbaktivitet/internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: veilarbaktivitet/internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 2
    max: 8
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 4048Mi
    requests:
      cpu: 200m
      memory: 1536Mi
  envFrom:
    - secret: veilarbaktivitet-unleash-api-token
  leaderElection: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    inbound:
      rules:
        - application: veilarbapi
          namespace: pto
          cluster: prod-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: prod-fss
        - application: aktivitetsplan
          namespace: pto
          cluster: prod-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: prod-gcp
    outbound:
      external:
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: veilarbaktivitet.prod-fss-pub.nais.io
        - host: veilarbarena.prod-fss-pub.nais.io
        - host: veilarbdialog.prod-fss-pub.nais.io
        - host: dab-unleash-api.nav.cloud.nais.io
        - host: orkivar.intern.nav.no
      rules:
        - application: poao-tilgang
          namespace: poao
  gcp:
    sqlInstances:
      - name: veilarbaktivitet-gcp
        type: POSTGRES_14
        tier: db-custom-8-53248 #TODO reduser etter migrering?
        diskType: SSD
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: false #TODO sett på før prodsetting
        flags: # Nødvendig for datastreams
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: veilarbaktivitet
            envVarPrefix: DB
            users:
              - name: datastream
  env:
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: ARENA_AKTIVITET_DATOFILTER
      value: "2017-12-04"
    - name: ORKIVAR_URL
      value: "https://orkivar.intern.nav.no"
    - name: VEILARBDIALOG_URL
      value: "https://veilarbdialog.prod-fss-pub.nais.io"
    - name: KAFKA_ENABLED
      value: "false"
    - name: AKTIVITETSPLAN_URL
      value: "https://aktivitetsplan.nav.no"
    - name: VEILARBOPPFOLGINGAPI_URL
      value: "https://veilarboppfolging.prod-fss-pub.nais.io"
    - name: VEILARBARENA_URL
      value: "https://veilarbarena.prod-fss-pub.nais.io"
    - name: VEILARBAKTIVITET_FSS_URL
      value: "https://veilarbaktivitet.prod-fss-pub.nais.io"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io"
    - name: PDL_SCOPE
      value: "api://prod-fss.pdl.pdl-api/.default"
    - name: FSS_PROXY_ENABLED
      value: "true"
