kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbaktivitet
  namespace: dab
  labels:
    team: dab
  annotations:
    config.linkerd.io/proxy-cpu-limit: 500m
spec:
  image: {{image}}
  ingresses:
    - https://veilarbaktivitet.intern.nav.no
  port: 8080
  prometheus:
    enabled: true
    path: /veilarbaktivitet/internal/prometheus
  liveness:
    path: /veilarbaktivitet/internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: /veilarbaktivitet/internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 2
    max: 8
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4048Mi
    requests:
      cpu: 200m
      memory: 1536Mi
  envFrom:
    - secret: veilarbaktivitet-unleash-api-token
    - secret: veilarbaktivitet-kassering-identer
  leaderElection: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    inbound:
      rules:
        - application: veilarbapi
          namespace: pto
          cluster: prod-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: prod-fss
        - application: veilarbdirigent
          namespace: dab
        - application: aktivitetsplan
          namespace: pto
          cluster: prod-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: prod-gcp
        - application: inngar
          namespace: dab
          cluster: prod-gcp
        - application: veilarbarena
          cluster: prod-fss
          namespace: pto
        - application: poao-admin
          cluster: prod-gcp
          namespace: poao
    outbound:
      external:
        - host: veilarbarena.prod-fss-pub.nais.io
        - host: veilarbdialog.intern.nav.no
        - host: dab-unleash-api.nav.cloud.nais.io
        - host: axsys.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
      rules:
        - application: poao-tilgang
          namespace: poao
        - application: veilarbdialog
          namespace: dab
        - application: veilarboppfolging
          namespace: poao
        - application: orkivar
  gcp:
    sqlInstances:
      - name: veilarbaktivitet-gcp
        type: POSTGRES_14
        tier: db-custom-8-53248 #TODO reduser etter migrering?
        diskType: SSD
        diskAutoresize: true
        highAvailability: true
        pointInTimeRecovery: true
        flags: # Nødvendig for datastreams
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: veilarbaktivitet
            envVarPrefix: DB
            users:
              - name: datastream
    bigQueryDatasets:
      - description: Funksjonelle metrikker for aktivitetsplan
        name: aktivitet_metrikker
        permission: READWRITE
  env:
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: ARENA_AKTIVITET_DATOFILTER
      value: "2017-12-04"
    - name: ORKIVAR_URL
      value: "http://orkivar"
    - name: VEILARBDIALOG_URL
      value: "https://veilarbdialog.intern.nav.no"
    - name: KAFKA_ENABLED
      value: "true"
    - name: AKTIVITETSPLAN_URL
      value: "https://aktivitetsplan.nav.no"
    - name: VEILARBOPPFOLGINGAPI_URL
      value: "http://veilarboppfolging.poao"
    - name: VEILARBARENA_URL
      value: "https://veilarbarena.prod-fss-pub.nais.io"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io"
    - name: PDL_SCOPE
      value: "api://prod-fss.pdl.pdl-api/.default"
    - name: PDL_SCOPE_TOKENX
      value: "prod-fss:pdl:pdl-api"
