apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: veilarbaktivitet
  namespace: dab
  labels:
    team: dab
spec:
  ingresses:
    - https://veilarbaktivitet.dev.nav.cloud.nais.io
  image: {{image}}
  port: 8080
  ttl: 3h
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  gcp:
    sqlInstances:
      - name: veilarbaktivitet
        type: POSTGRES_14
        databases:
          - name: veilarbaktivitet
            envVarPrefix: DB