kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbaktivitet
  namespace: dab
  labels:
    team: dab
spec:
  image: {{image}}
  ingresses:
    - https://veilarbaktivitet.dev.nav.cloud.nais.io
    - https://veilarbaktivitet.intern.dev.nav.no
  port: 8080
  prometheus:
    enabled: true
    path: veilarbaktivitet/internal/prometheus
  liveness:
    path: veilarbaktivitet/internal/isAlive
    port: 8080
    initialDelay: 60
    timeout: 10
  readiness:
    path: veilarbaktivitet/internal/isReady
    port: 8080
    initialDelay: 60
    timeout: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  envFrom:
    - secret: veilarbaktivitet-unleash-api-token
    - secret: veilarbaktivitet-kassering-identer
  leaderElection: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java

  accessPolicy:
    inbound:
      rules:
        - application: veilarbapi
          namespace: pto
          cluster: dev-gcp
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: veilarbdirigent
          namespace: pto
          cluster: dev-fss
        - application: aktivitetsplan
          namespace: pto
          cluster: dev-gcp
        - application: arbeidsrettet-dialog
          namespace: pto
          cluster: dev-gcp
        - application: ida
          namespace: traktor
          cluster: prod-fss # Dette er med vilje
    outbound:
      external:
        - host: veilarbarena.dev-fss-pub.nais.io
        - host: veilarbdialog.intern.dev.nav.no
        - host: dab-unleash-api.nav.cloud.nais.io
        - host: axsys.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
      rules:
        - application: poao-tilgang
          namespace: poao
        - application: veilarbdialog
          namespace: dab
        - application: veilarboppfolging
          namespace: poao
        - application: orkivar
  gcp:
    sqlInstances:
      - name: veilarbaktivitet
        type: POSTGRES_14
        tier: db-custom-1-3840
        diskType: SSD
        diskAutoresize: true
        flags: # Nødvendig for datastreams
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: veilarbaktivitet
            envVarPrefix: DB
            users:
              - name: datastream
    bigQueryDatasets:
      - description: Funksjonelle metrikker for aktivitetsplan
        name: aktivitet_metrikker
        permission: READWRITE
  env:
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: ARENA_AKTIVITET_DATOFILTER
      value: "2017-12-04"
    - name: ORKIVAR_URL
      value: "http://orkivar"
    - name: VEILARBDIALOG_URL
      value: "https://veilarbdialog.intern.dev.nav.no"
    - name: KAFKA_ENABLED
      value: "true"
    - name: AKTIVITETSPLAN_URL
      value: "https://aktivitetsplan.ekstern.dev.nav.no"
    - name: VEILARBOPPFOLGINGAPI_URL
      value: "http://veilarboppfolging.poao"
    - name: VEILARBARENA_URL
      value: "https://veilarbarena.dev-fss-pub.nais.io"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
    - name: FSS_PROXY_ENABLED
      value: "false"
    - name: AXSYS_URL
      value: "https://axsys.dev-fss-pub.nais.io"
