INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('REFERAT_OPPRETTET', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('BLE_HISTORISK', CURRENT_TIMESTAMP, 'KASSERT');
