INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('FATT_JOBBEN', CURRENT_TIMESTAMP, 'SIGURD :)');

ALTER TABLE STILLING_FRA_NAV RENAME COLUMN IKKEFATTJOBBENDETALJER TO DETALJER