CREATE TABLE ARENA_KONVERTERING
(
  ARENA_AKTIVITET_ID   NVARCHAR2(255) NOT NULL
    CONSTRAINT ARENA_AKTIVITET_ID_PK
    PRIMARY KEY,
  ARENA_AKTIVITET_TYPE NVARCHAR2(255) NOT NULL,
  KONVERT_DATO         TIMESTAMP(6)   NOT NULL,
  AKTIVITET_ID         NVARCHAR2(255) NOT NULL
);

