CREATE OR REPLACE VIEW DVH_AKTIVITET AS (
SELECT
    AKTIVITET_ID,
    VERSJON,
    TRANSAKSJONS_TYPE,
    AKTOR_ID,
    TITTEL,
    AKTIVITET_TYPE_KODE,
    AVSLUTTET_KOMMENTAR,
    LAGT_INN_AV,
    FRA_DATO,
    TIL_DATO,
    LENKE,
    OPPRETTET_DATO,
    ENDRET_DATO,
    ENDRET_AV,
    LIVSLOPSTATUS_KODE,
    BESKRIVELSE,
    AVTALT AS AVTALT_FLAGG,
    HISTORISK_DATO,
    GJELDENDE AS GJELDENDE_FLAGG,
    OPPFOLGINGSPERIODE_UUID
FROM AKTIVITET where AKTIVITET_TYPE_KODE != 'EKSTERNAKTIVITET'
    );
