INSERT INTO AKTIVITET_TYPE (AKTIVITET_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('EGENAKTIVITET', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO AKTIVITET_TYPE (AKTIVITET_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('JOBBSOEKING', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO AKTIVITET_TYPE (AKTIVITET_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('SOKEAVTALE', CURRENT_TIMESTAMP, 'KASSERT');


INSERT INTO AKTIVITET_LIVSLOPSTATUS_TYPE (AKTIVITET_LIVSLOP_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('PLANLAGT', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO AKTIVITET_LIVSLOPSTATUS_TYPE (AKTIVITET_LIVSLOP_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('GJENNOMFORT', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO AKTIVITET_LIVSLOPSTATUS_TYPE (AKTIVITET_LIVSLOP_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('FULLFORT', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO AKTIVITET_LIVSLOPSTATUS_TYPE (AKTIVITET_LIVSLOP_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('BRUKER_ER_INTERESSERT', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO AKTIVITET_LIVSLOPSTATUS_TYPE (AKTIVITET_LIVSLOP_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('AVBRUTT', CURRENT_TIMESTAMP, 'KASSERT');


INSERT INTO STILLINGSSOK_ETIKETT_TYPE (ETIKETT_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('SOKNAD_SENDT', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO STILLINGSSOK_ETIKETT_TYPE (ETIKETT_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('INNKALT_TIL_INTERVJU', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO STILLINGSSOK_ETIKETT_TYPE (ETIKETT_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('AVSLAG', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO STILLINGSSOK_ETIKETT_TYPE (ETIKETT_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('JOBBTILBUD', CURRENT_TIMESTAMP, 'KASSERT');


INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('OPPRETTET', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('STATUS_ENDRET', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('DETALJER_ENDRET', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('AVTALT', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('AVTALT_DATO_ENDRET', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO TRANSAKSJONS_TYPE (TRANSAKSJONS_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('ETIKETT_ENDRET', CURRENT_TIMESTAMP, 'KASSERT');
