CREATE VIEW DVH_JOBB_STATUS_TYPE AS (
  SELECT
    JOBB_STATUS_KODE,
    OPPRETTET_DATO,
    OPPRETTET_AV,
    ENDRET_DATO,
    ENDRET_AV
  FROM JOBB_STATUS_TYPE
);

CREATE VIEW DVH_IJOBB AS (
  SELECT
    AKTIVITET_ID,
    VERSJON,
    JOBB_STATUS,
    ANSETTELSESFORHOLD,
    ARBEIDSTID
  FROM IJOBB
);
