CREATE TABLE FEILEDE_KAFKA_MELDINGER
(
    MELDING_ID NVARCHAR2(50)       NOT NULL
        CONSTRAINT FEILEDE_KAFKA_MELDINGER_PK PRIMARY KEY,
    AKTIVITET_ID     NUMBER(19)          NOT NULL,
    AKTOR_ID         VARCHAR2(50)        NOT NULL,
    FRA_DATO         TIMESTAMP(6)        NOT NULL,
    TIL_DATO         TIMESTAMP(6)        NOT NULL,
    ENDRET_DATO      TIMESTAMP(6)        NOT NULL,
    AKTIVITET_TYPE   NVARCHAR2(50)       NOT NULL,
    AKTIVITET_STATUS NVARCHAR2(50)       NOT NULL,
    AVTALT           NUMBER(1) DEFAULT 0 NOT NULL,
    HISTORISK        NUMBER(1) DEFAULT 0 NOT NULL
);
