INSERT INTO AKTIVITET_TYPE (AKTIVITET_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('BEHANDLING', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO AKTIVITET_TYPE (AKTIVITET_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('IJOBB', CURRENT_TIMESTAMP, 'KASSERT');

CREATE TABLE JOBB_STATUS_TYPE
(
  JOBB_STATUS_KODE    NVARCHAR2(255) NOT NULL
    CONSTRAINT JOBB_STATUS_PK
    PRIMARY KEY,
  OPPRETTET_DATO      TIMESTAMP(6)   NOT NULL,
  OPPRETTET_AV        NVARCHAR2(255) NOT NULL,
  ENDRET_DATO         TIMESTAMP(6),
  ENDRET_AV           NVARCHAR2(255)
);

INSERT INTO JOBB_STATUS_TYPE (JOBB_STATUS_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('HELTID', CURRENT_TIMESTAMP, 'KASSERT');

INSERT INTO JOBB_STATUS_TYPE (JOBB_STATUS_KODE, OPPRETTET_DATO, OPPRETTET_AV)
VALUES ('DELTID', CURRENT_TIMESTAMP, 'KASSERT');

CREATE TABLE BEHANDLING
(
  AKTIVITET_ID          NUMBER(19),
  VERSJON               NUMBER(19) DEFAULT 0 NOT NULL,
  BEHANDLING_STED       NVARCHAR2(255),
  EFFEKT                NVARCHAR2(255),
  BEHANDLING_OPPFOLGING NVARCHAR2(255),
  CONSTRAINT BEHANDLING_FK FOREIGN KEY (AKTIVITET_ID, VERSJON) REFERENCES AKTIVITET,
  CONSTRAINT BEHANDLING_PK PRIMARY KEY (AKTIVITET_ID, VERSJON)
);

CREATE TABLE IJOBB
(
  AKTIVITET_ID       NUMBER(19),
  VERSJON            NUMBER(19) DEFAULT 0 NOT NULL,
  JOBB_STATUS        NVARCHAR2(255)
    CONSTRAINT JOBB_STATUS_TYPE_FK
    REFERENCES JOBB_STATUS_TYPE,
  ANSETTELSESFORHOLD NVARCHAR2(255),
  ARBEIDSTID         NVARCHAR2(255),
  CONSTRAINT IJOBB_FK FOREIGN KEY (AKTIVITET_ID, VERSJON) REFERENCES AKTIVITET,
  CONSTRAINT IJOBB_PK PRIMARY KEY (AKTIVITET_ID, VERSJON)
);
