CREATE OR REPLACE VIEW DVH_SOKEAVTALE_AKTIVITET AS (
  SELECT
    SOKEAVTALE.AKTIVITET_ID,
    SOKEAVTALE.VERSJON,
    SOKEAVTALE.ANTALL_STILLINGER_SOKES,
    SOKEAVTALE.AVTALE_OPPFOLGING,
    AKTIVITET.ENDRET_DATO
  FROM SOKEAVTALE
  LEFT JOIN AKTIVITET ON SOKEAVTALE.AKTIVITET_ID = AKTIVITET.AKTIVITET_ID AND SOKEAVTALE.VERSJON = AKTIVITET.VERSJON
);

CREATE OR REPLACE VIEW DVH_AKTIVITET AS (
  SELECT
    AKTIVITET_ID,
    VERSJON,
    TRANSAKSJONS_TYPE,
    AKTOR_ID,
    TITTEL,
    AKTIVITET_TYPE_KODE,
    AVSLUTTET_DATO,
    AVSLUTTET_KOMMENTAR,
    LAGT_INN_AV,
    FRA_DATO,
    TIL_DATO,
    LENKE,
    OPPRETTET_DATO,
    ENDRET_DATO,
    ENDRET_AV,
    LIVSLOPSTATUS_KODE,
    BESKRIVELSE,
    AVTALT,
    HISTORISK_DATO,
    GJELDENDE
  FROM AKTIVITET
);