CREATE TABLE EKSTERNAKTIVITET
(
    AKTIVITET_ID NUMBER(19),
    VERSJON      NUMBER(19) DEFAULT 0 NOT NULL,
    SOURCE       NVARCHAR2(255),
    TILTAK_KODE  NVARCHAR2(255),
    AKTIVITETKORT_TYPE NVARCHAR2(255),
    OPPGAVE      CLOB,
    HANDLINGER   CLOB,
    DETALJER     CLOB,
    ETIKETTER    CLOB,
    CONSTRAINT EKSTERNAKTIVITET_FK FOREIGN KEY (AKTIVITET_ID, VERSJON) REFERENCES AKTIVITET,
    CONSTRAINT EKSTERNAKTIVITET_PK PRIMARY KEY (AKTIVITET_ID, VERSJON),
    CONSTRAINT ensure_json CHECK (OPPGAVE IS JSON and HANDLINGER IS JSON and DETALJER IS JSON and ETIKETTER is JSON)
);

DROP TABLE TILTAKSAKTIVITET;