ALTER TABLE OPPFOLGINGSPERIODE ADD aktorIdFiks VARCHAR2(20);
UPDATE OPPFOLGINGSPERIODE SET aktorIdFiks = TRIM(AKTORID);
ALTER TABLE OPPFOLGINGSPERIODE DROP COLUMN AKTORID;
ALTER TABLE OPPFOLGINGSPERIODE RENAME COLUMN aktorIdFiks TO AKTORID;
