CREATE TABLE ARENA_FORHAANDSORIENTERING (
    ARENAAKTIVITET_ID NVARCHAR2(255) NOT NULL,
    AKTOR_ID NVARCHAR2(255) NOT NULL,
    FHO_TYPE NVARCHAR2(255) NOT NULL,
    FHO_TEKST NVARCHAR2(1000) NOT NULL,
    FHO_OPPRETTET_DATO TIMESTAMP(6) NOT NULL,

    CONSTRAINT ARENA_FORHAANDSORIENTERING_PK PRIMARY KEY (ARENAAKTIVITET_ID)
);

CREATE INDEX ARENA_FORHAANDSORIENTERING_INDEX ON ARENA_FORHAANDSORIENTERING (AKTOR_ID);
