
CREATE TABLE AKTIVITET_SENDT_PAA_KAFKA (
    AKTIVITET_ID NUMBER(19) NOT NULL,
    AKTIVITET_VERSJON NUMBER(19) NOT NULL,
    SENDT TIMESTAMP not null,

    CONSTRAINT AKTIVITET_SENDT_PAA_KAFKA_PK PRIMARY KEY (AKTIVITET_ID, AKTIVITET_VERSJON),
    CONSTRAINT KAFKA_TIL_AKTIVITET FOREIGN KEY (AKTIVITET_ID, AKTIVITET_VERSJON) REFERENCES AKTIVITET(AKTIVITET_ID, VERSJON)
);
