create table VARSEL
(
    id            number(19) generated by default as identity primary key,
    varsel_id     varchar(255) not null,
    aktivitet_id  number(19) not null,
    varsel_type   varchar(255) not null,
    varsel_status varchar(255) not null,
    sendt         timestamp    not null,
    varsel_feilet timestamp,
    avsluttet     timestamp,
    CONSTRAINT VARSELL_FK FOREIGN KEY (AKTIVITET_ID) REFERENCES AKTIVITET
);
