create table JOBB
     (
        id number(19) generated by default as identity
        primary key,
        jobbtype varchar(255) not null,
        aktivitet_id number(19) not null,
        versjon number(19) not null,
        status varchar(255) NOT NULL,
        CONSTRAINT JOBB_FK FOREIGN KEY (AKTIVITET_ID, VERSJON) REFERENCES AKTIVITET
    );

