
create table STILLING_FRA_NAV(
    AKTIVITET_ID number(19) not null,
    VERSJON number(19) not null,
    CV_KAN_DELES number(1),
    CV_KAN_DELES_TIDSPUNKT timestamp,
    CV_KAN_DELES_AV nvarchar2(255),
    CV_KAN_DELES_AV_TYPE nvarchar2(255),

    CONSTRAINT STILLING_FRA_NAV_FK FOREIGN KEY (AKTIVITET_ID, VERSJON) REFERENCES AKTIVITET,
    CONSTRAINT STILLING_FRA_NAV_PK PRIMARY KEY (AKTIVITET_ID, VERSJON)
);

INSERT INTO AKTIVITET_TYPE (AKTIVITET_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV,ENDRET_AV,ENDRET_DATO)
VALUES ('STILLING_FRA_NAV', CURRENT_TIMESTAMP, 'KASSERT','KASSERT', CURRENT_TIMESTAMP);
