CREATE TABLE FORHAANDSORIENTERING (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    AKTOR_ID VARCHAR(20) NOT NULL,

    ARENAAKTIVITET_ID NVARCHAR2(255),
    AKTIVITET_ID NUMBER(19),
    AKTIVITET_VERSJON NVARCHAR2(255),

    TYPE NVARCHAR2(50) NOT NULL,
    TEKST NVARCHAR2(1000),
    OPPRETTET_DATO TIMESTAMP(6) NOT NULL,
    OPPRETTET_AV VARCHAR(20) NOT NULL,
    LEST_DATO TIMESTAMP(6),
    LEST_AKTIVITET_VERSJON NVARCHAR2(255),
    VARSEL_ID CHAR(36),
    VARSEL_STOPPET TIMESTAMP(6),

    CONSTRAINT ID_PK PRIMARY KEY (ID),

    CONSTRAINT AKTIVITET_REF_CHK
        CHECK (
        ( ARENAAKTIVITET_ID IS NOT NULL AND AKTIVITET_ID IS NULL ) OR
        ( ARENAAKTIVITET_ID IS NULL AND AKTIVITET_ID IS NOT NULL )
        )

);

