update BRUKERNOTIFIKASJON
set VARSEL_KVITTERING_STATUS = 'OK',
    STATUS                   = 'SENDT'
where STATUS = 'SENDT_OK';

update BRUKERNOTIFIKASJON
set VARSEL_KVITTERING_STATUS = 'FEILET',
    STATUS                   = 'SENDT'
where STATUS = 'FEILET';

alter table BRUKERNOTIFIKASJON MODIFY
(
    VARSEL_KVITTERING_STATUS varchar (255) DEFAULT (NULL)
);