insert into AKTIVITET_BRUKERNOTIFIKASJON (AKTIVITET_ID, OPPRETTET_PAA_AKTIVITET_VERSION, BRUKERNOTIFIKASJON_ID)
select AKTIVITET_ID, OPPRETTET_PAA_AKTIVITET_VERSION, ID from BRUKERNOTIFIKASJON b
where not exists(select * from AKTIVITET_BRUKERNOTIFIKASJON a2 where a2.BRUKERNOTIFIKASJON_ID = b.ID);

alter table AKTIVITET_BRUKERNOTIFIKASJON drop column AVSLUTTET_PAA_AKTIVITET_VERSION;