CREATE TABLE TILTAKSAKTIVITET
(
    AKTIVITET_ID       NUMBER(19),
    VERSJON            NUMBER(19) DEFAULT 0 NOT NULL,
    TILTAK_KODE        NVARCHAR2(255),
    TILTAK_NAVN        NVARCHAR2(255),
    AARSAK             NVARCHAR2(255),
    ARRANGOR_NAVN      NVARCHAR2(255),
    DELTAKELSEPROSENT  NUMBER(19),
    DAGER_PER_UKE      NUMBER(19),
    REGISTRERT_DATO    TIMESTAMP(6),
    STATUS_ENDRET_DATO TIMESTAMP(6),
    CONSTRAINT TILTAKSAKTIVITET_FK FOREIGN KEY (AKTIVITET_ID, VERSJON) REFERENCES AKTIVITET,
    CONSTRAINT TILTAKSAKTIVITET_PK PRIMARY KEY (AKTIVITET_ID, VERSJON)
);

INSERT INTO AKTIVITET_TYPE (AKTIVITET_TYPE_KODE, OPPRETTET_DATO, OPPRETTET_AV, ENDRET_AV, ENDRET_DATO)
VALUES ('TILTAKSAKTIVITET', CURRENT_TIMESTAMP, 'KASSERT', 'KASSERT', CURRENT_TIMESTAMP);

CREATE TABLE ID_MAPPINGER
(
    AKTIVITET_ID         NUMBER(19),
    FUNKSJONELL_ID       VARCHAR(40),
    EKSTERN_REFERANSE_ID VARCHAR(40),
    SOURCE               NVARCHAR2(255),
    CONSTRAINT ID_MAPPINGER_PK PRIMARY KEY (FUNKSJONELL_ID)
);

