CREATE TABLE TILTAKSAKTIVITET
(
    AKTIVITET_ID       NUMBER(19),
    VERSJON            NUMBER(19) DEFAULT 0 NOT NULL,
    TILTAK_KODE        NVARCHAR2(255),
    TILTAK_NAVN        NVARCHAR2(255),
    ARRANGOR_NAVN      NVARCHAR2(255),
    DELTAKELSESTATUS   NVARCHAR2(255),
    DAGER_PER_UKE      NUMBER(19),
    DELTAKELSEPROSENT  NUMBER(19),
    CONSTRAINT TILTAKSAKTIVITET_FK FOREIGN KEY (AKTIVITET_ID, VERSJON) REFERENCES AKTIVITET,
    CONSTRAINT TILTAKSAKTIVITET_PK PRIMARY KEY (AKTIVITET_ID, VERSJON)
);
