name: Deploy alerts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'nais/alerts-feilrate.yaml'
      - '.github/workflows/alerts-nye.yml'

concurrency:
  group: deploy_alerts_nye
  cancel-in-progress: true

jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/alerts-feilrate.yaml
      - name: deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/alerts-feilrate.yaml
