name: Deploy alerts to dev
on:
  push:
    branches:
      - dev
    paths:
      - 'alerts-dev.yaml'
      - 'alerts-dev-arena.yaml'
      - '.github/workflows/alerts-dev.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: alerts-dev.yaml
      - name: deploy arena alert
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: alerts-dev-arena.yaml
