name: Deploy alerts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'nais/alerts-prod.yaml'
      - 'nais/alerts-prod-low-priority.yaml'
      - 'nais/alerts-dev.yaml'
      - 'nais/alerts-dev-low-priority.yaml'
      - '.github/workflows/alerts.yaml'

concurrency:
  group: deploy_alerts_prod
  cancel-in-progress: true

jobs:
  apply-alerts-dev:
    name: Apply alerts to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/alerts-dev.yaml
      - name: deploy arena alert
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/alerts-dev-low-priority.yaml

  apply-alerts-prod:
    name: Apply alerts to prod
    runs-on: ubuntu-latest
    needs: apply-alerts-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/alerts-prod.yaml
      - name: deploy arena alert
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/alerts-prod-low-priority.yaml
