name: Deploy alerts to prod
on:
  push:
    branches:
      - master
    paths:
      - 'alerts-prod.yaml'
      - '.github/workflows/alerts-prod.yaml'
      - '.github/workflows/alerts-prod-arena.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: alerts-prod.yaml
      - name: deploy arena alert
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: alerts-prod-arena.yaml
