name: Deploy nye alerts til dev
on:
  workflow_dispatch:

concurrency:
  group: deploy_alerts_nye_dev
  cancel-in-progress: true

jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: deploy to dev-gcp
        uses: nais/deploy/actions/deploy@027a91857992525139798892f2804b0ca21f4af6
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/alerts-feilrate.yaml
