name: AsyncAPI documents processing

on:
  push:


jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generating HTML from my AsyncAPI document
        working-directory: ./src/main/resources/schemas/
        uses: docker://asyncapi/github-action-for-generator:2.1.8

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        working-directory: ./src/main/resources/schemas/
        with:
          folder: generated-html