name: AsyncAPI documents processing

on:
  push:


jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v3


      - name: Generating HTML from my AsyncAPI document
        uses: docker://asyncapi/github-action-for-generator:2.1.8
        with:
          filepath: src/main/resources/schemas/AktivitetskortV1.asyncapi.yml
          output: generated-html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: generated-html