name: AsyncAPI documents processing

on:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: install generator
        run: npm install -g @asyncapi/generator

      - name: generate documentaion (denne tar litt tid)
        run: ag ./src/main/resources/schemas/AktivitetskortV1.asyncapi.yml @asyncapi/html-template -o aktivitetskortV1-doc  --force-write

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: aktivitetskortV1-doc