name: deploy feture branch
on:
  workflow_dispatch:

concurrency:
  group: deploy_feture_branch
  cancel-in-progress: true

env:
  IMAGE_TAG: ${{ github.sha }}-dev-only
  IMAGE: docker.pkg.github.com/${{ github.repository }}/veilarbaktivitet
  PRINT_PAYLOAD: true
jobs:
  test-build-and-push:
    name: Test, build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build maven artifacts
        run: mvn -B package
      - name: Build and push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker build nais/Dockerfile -t ${IMAGE}:${IMAGE_TAG} .
          docker push ${IMAGE}:${IMAGE_TAG}

  deploy-dev:
    name: Deploy application to Q1
    needs: test-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/nais-q.yaml
          VAR: version=${{ env.IMAGE_TAG }},namespace=q1
