name: Deploy kafka topics to dev
on:
  push:
    branches:
      - main
    paths:
      - "kafka-topic/dev/*.yaml"
  workflow_dispatch:

jobs:
  deploy-topics-dev:
    name: Deploy kafka topics to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: List resource files
        run: echo "RESOURCE_FILES=$(find kafka-topic/dev -type f | tr '\n' ',' | sed 's/,$/\n/')" >> $GITHUB_ENV
      - name: Deploy kafka topics
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ env.RESOURCE_FILES }}
          PRINT_PAYLOAD: true
