name: Deploy kafka topics to prod
on:
  push:
    branches:
      - main
    paths:
      - "kafka-topic/prod/*.yaml"
  workflow_dispatch:

jobs:
  deploy-topics-prod:
    name: Deploy kafka topics to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List resource files
        run: echo "RESOURCE_FILES=$(find kafka-topic/prod -type f | tr '\n' ',' | sed 's/,$/\n/')" >> $GITHUB_ENV
      - name: Deploy kafka topics
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.DAB_NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: ${{ env.RESOURCE_FILES }}
          PRINT_PAYLOAD: true
