name: Unleash api-tokens

on:
  push:
    branches:
      - main
      - gcp-main
    paths:
      - '.github/workflows/unleash-apitoken.yaml'
      - 'nais/unleash-apitoken-dev.yaml'
      - 'nais/unleash-apitoken.yaml'
      - 'nais/unleash-apitoken-dev-gcp.yaml'
      - 'nais/unleash-apitoken-gcp.yaml'

jobs:
  apply-apitoken-unleash:
    name: Apply ApiToken for Unleash to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/unleash-apitoken-dev.yaml
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/unleash-apitoken.yaml
      - name: deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/unleash-apitoken-dev-gcp.yaml
      - name: deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/unleash-apitoken-gcp.yaml
