truncate table OPPFOLGINGSPERIODE;

insert into
    OPPFOLGINGSPERIODE (ID, AKTORID, FRA, TIL)
SELECT UUID as id, AKTOR_ID as AKTORID, STARTDATO as FRA, SLUTTDATO as TIL
from OPPFOLGINGSPERIODE@VEILARBOPPFOLGING;
